#pragma once

#include "General/Transform2DComponent.hpp"
#include "General/RectTransform2DComponent.hpp"
#include "General/NameComponent.hpp"
#include "General/UUIDComponent.hpp"
#include "General/EntityMetaDataComponent.hpp"
#include "General/PrefabInstanceComponent.hpp"
#include "General/HierarchyComponent.hpp"

#include "Graphics/SpriteRendererComponent.hpp"
#include "Graphics/ImageComponent.hpp"
#include "Graphics/Camera2DComponent.hpp"
#include "Graphics/ParticleSystem2DComponent.hpp"
#include "Graphics/TextRendererComponent.hpp"

#include "Physics/BoxCollider2DComponent.hpp"
#include "Physics/CircleCollider2DComponent.hpp"
#include "Physics/PolygonCollider2DComponent.hpp"
#include "Physics/Rigidbody2DComponent.hpp"

#include "Physics/FastBody2DComponent.hpp"
#include "Physics/FastBoxCollider2DComponent.hpp"
#include "Physics/FastCircleCollider2DComponent.hpp"

#include "Audio/AudioSourceComponent.hpp"
#include "Scripting/ScriptComponent.hpp"

#include "UI/InteractableComponent.hpp"
#include "UI/ButtonComponent.hpp"
#include "UI/SliderComponent.hpp"
#include "UI/InputFieldComponent.hpp"
#include "UI/DropdownComponent.hpp"
#include "UI/ToggleComponent.hpp"
#include "UI/ScrollbarComponent.hpp"
#include "UI/ScrollRectComponent.hpp"
#include "UI/MaskComponent.hpp"
#include "UI/ContentSizeFitterComponent.hpp"
#include "UI/WidthConstraintComponent.hpp"
#include "UI/CircularSliderComponent.hpp"
#include "UI/HorizontalLayoutGroupComponent.hpp"
#include "UI/VerticalLayoutGroupComponent.hpp"
#include "UI/GridLayoutGroupComponent.hpp"

#include "Tags.hpp"
